mutation AddTag($name: String!) {
  addTag(tagName: $name) {
    id
    name
  }
}

mutation CreateUsers($userName: String!) {
  createUsers (input: {
    name: $userName
  }) {
    info {
      nodesCreated
    }
  }
}