version: "3.6"

services:
  #GQL Gateway
  gatewayapi:
    image: gatewayapi
    build:
      context: ./GatewayApi
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5050;
      - Services__TagsApi__endpoint=http://tagsapi:5010
    ports:
      - "5050:5050"
    expose:
      - "5050"
    depends_on:
      - tagsapi
      - likesapi
  # WEBAPI MONGODB
  tagsapi:
    image: tagsapi
    build:
      context: ./TagsApi
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5010;
    ports:
      - "5010:5010"
    expose:
      - "5010"
  likesapi:
    image: likesapi
    build:
      context: ./LikesApi
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    expose:
      - "4000"
  neo4j:
    image: neo4j:5.5.0
    restart: unless-stopped
    ports:
      - "7474:7474"