mutation AddTag($name: String!) {
  addTag(name: $name) {
    tag {
      name
    }
  }
}

mutation CreateUsers(
  $userAccount: String!
  $userName: String!
  $userImage: String!
  $userBio: String!
) {
  createUsers(
    input: {
      account: $userAccount
      name: $userName
      image: $userImage
      bio: $userBio
    }
  ) {
    info {
      nodesCreated
    }
  }
}

mutation UpdateUsers($userAccount: String!, $technologyName: String!) {
  updateUsers(
    connectOrCreate: {
      technologies: {
        where: { node: { name: $technologyName } }
        onCreate: { node: { name: $technologyName } }
      }
    }
    where: { account: $userAccount }
  ) {
    info {
      nodesCreated
      relationshipsCreated
    }
  }
}

mutation DetachUsers($userAccount: String!, $technologyName: String!) {
  updateUsers(
    disconnect: { technologies: { where: { node: { name: $technologyName } } } }
    where: { account: $userAccount }
  ) {
    info {
      relationshipsDeleted
    }
  }
}
