query GetTags {
  tags {
    name
  }
}

query User($userAccount: String!) {
  users(where: { account: $userAccount }) {
    account
    name
    image
    bio
    technologies {
      name
    }
  }
}

query GetRecommendation($userAccount: String!) {
  users(where: { account: $userAccount }) {
    technologies {
      users(where: { NOT: { account: $userAccount } }) {
        account
        name
        image
        bio
        technologies {
          name
        }
      }
    }
  }
}
